package io.github.mayusi.calibratesoc.data.script

import io.github.mayusi.calibratesoc.data.capability.CapabilityReport
import io.github.mayusi.calibratesoc.data.devicedb.DeviceAdapter
import io.github.mayusi.calibratesoc.data.presets.Preset
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Converts a [Preset] into a bash script byte-compatible with the
 * pattern from TheOldTaylor's Odin3-CPU-Underclock repo. The user then
 * invokes the script via Odin Settings -> "Run script as Root" — that
 * UI path executes shell scripts under root *without* the user needing
 * to install Magisk or KernelSU.
 *
 * Script body uses the same recipe TheOldTaylor proved works on the
 * 8 Elite firmware:
 *
 *   1. stop vendor perf daemons (per-device, from DeviceAdapter)
 *   2. chmod 666 the target so a stock `echo >` succeeds
 *   3. write the value with printf (echo's trailing newline upsets
 *      some kernel parsers)
 *   4. chmod 444 to seal — the daemons can restart but they can't
 *      clobber the value because they no longer have write permission
 *
 * The generated script is self-contained — no external dependencies,
 * no embedded values from our app, no networking. Easy to audit before
 * running.
 */
@Singleton
class AynScriptGenerator @Inject constructor() {

    /**
     * Build a shell script string for [preset]. Caller writes the
     * return value to disk via [AynScriptDeployer].
     */
    fun generate(preset: Preset, report: CapabilityReport, adapter: DeviceAdapter?): String {
        val daemons = adapter?.perfDaemonsToStopOnWrite.orEmpty()
        val chmodLock = adapter?.chmodLockCpuFreqWrites ?: false

        return buildString {
            appendLine("#!/system/bin/sh")
            appendLine("# Generated by Calibrate SoC for ${report.device.manufacturer} ${report.device.model}")
            appendLine("# Preset: ${preset.name}")
            appendLine("# ${preset.description}")
            preset.sourceUrl?.let { appendLine("# Source: $it") }
            appendLine("# This script writes to kernel sysfs and is invoked via")
            appendLine("# your device's settings -> Run script as Root. Sysfs writes")
            appendLine("# do not persist across reboot — re-run after each boot if needed.")
            appendLine()

            if (daemons.isNotEmpty()) {
                appendLine("# Stop vendor perf daemons so they cannot race the write.")
                appendLine("# 2>/dev/null: a daemon that isn't running on THIS firmware")
                appendLine("# must not abort the rest of the script.")
                daemons.forEach { appendLine("stop $it 2>/dev/null") }
                appendLine()
            }

            // Safety guard: refuse to emit min == max OR min > max OR
            // min > 1.5 GHz. All three patterns trap the CPU at high
            // freq and cause the "device cooks while idle" failure.
            // Caller must give us a properly-formed preset; if they
            // didn't, append a comment that explains why we skipped.
            val safeMins = mutableMapOf<Int, Int>()
            for ((policyId, minKhz) in preset.cpuPolicyMinKhz) {
                val maxKhz = preset.cpuPolicyMaxKhz[policyId]
                when {
                    minKhz > 1_500_000 -> {
                        appendLine("# SAFETY: skipping min for policy$policyId — min ${minKhz}kHz > 1.5 GHz would trap cores at high freq.")
                    }
                    maxKhz != null && minKhz >= maxKhz -> {
                        appendLine("# SAFETY: skipping min for policy$policyId — min ${minKhz}kHz >= max ${maxKhz}kHz would pin cores.")
                    }
                    else -> safeMins[policyId] = minKhz
                }
            }

            // Write min FIRST when we're LOWERING it, max FIRST when
            // RAISING. Otherwise the kernel rejects a write that
            // would temporarily violate min <= cur <= max. Easiest
            // safe order: always write min low first, then max,
            // then min final.
            safeMins.toSortedMap().forEach { (policyId, _) ->
                // Drop min to a guaranteed-safe floor before touching max.
                emitFreqWrite(policyId, "scaling_min_freq", 300000, chmodLock)
            }
            preset.cpuPolicyMaxKhz.toSortedMap().forEach { (policyId, khz) ->
                emitFreqWrite(policyId, "scaling_max_freq", khz, chmodLock)
            }
            safeMins.toSortedMap().forEach { (policyId, khz) ->
                emitFreqWrite(policyId, "scaling_min_freq", khz, chmodLock)
            }
            preset.cpuPolicyGovernor.toSortedMap().forEach { (policyId, gov) ->
                emitGovernorWrite(policyId, gov)
            }

            // GPU writes — Adreno + Mali both expose devfreq paths.
            // We use the GpuProbe's rootPath to be vendor-agnostic.
            val gpuRoot = report.gpu?.rootPath
            if (gpuRoot != null) {
                preset.gpuMinHz?.let { emitGpuWrite(gpuRoot, "devfreq/min_freq", it.toString()) }
                preset.gpuMaxHz?.let { emitGpuWrite(gpuRoot, "devfreq/max_freq", it.toString()) }
                preset.gpuGovernor?.let { emitGpuWrite(gpuRoot, "devfreq/governor", it) }
            }

            if (daemons.isNotEmpty()) {
                appendLine()
                appendLine("# Daemons stay stopped — restarting them re-enables the")
                appendLine("# race they were stopped to avoid. Reboot to restore them.")
            }

            // Verification block: read back every policy we touched so the
            // user (and Calibrate SoC's run-as-root output capture) can
            // confirm the values actually stuck. A line that shows the
            // OLD value here means perfd or a kernel min<=cur<=max
            // constraint clamped us — actionable signal, not a silent
            // failure.
            val touchedPolicies = (preset.cpuPolicyMaxKhz.keys + preset.cpuPolicyMinKhz.keys)
                .toSortedSet()
            if (touchedPolicies.isNotEmpty()) {
                appendLine()
                appendLine("echo '--- Calibrate SoC: verifying ---'")
                for (policyId in touchedPolicies) {
                    val base = "/sys/devices/system/cpu/cpufreq/policy$policyId"
                    appendLine(
                        "echo \"policy$policyId max=\$(cat $base/scaling_max_freq 2>/dev/null) " +
                            "min=\$(cat $base/scaling_min_freq 2>/dev/null) " +
                            "gov=\$(cat $base/scaling_governor 2>/dev/null)\"",
                    )
                }
            }
            appendLine()
            appendLine("echo 'Calibrate SoC: ${preset.name} applied.'")
        }
    }

    private fun StringBuilder.emitFreqWrite(
        policyId: Int,
        node: String,
        khz: Int,
        chmodLock: Boolean,
    ) {
        val path = "/sys/devices/system/cpu/cpufreq/policy$policyId/$node"
        // Guard the whole write on the path existing — policy IDs differ
        // per SoC (2 clusters on Odin, 3 on Thor/RP6/DS) and a missing
        // node must not abort the script.
        //
        // Redirect note: `printf > file 2>/dev/null` does NOT suppress a
        // "can't create: Permission denied" message, because the shell
        // opens the redirect target BEFORE running printf, so the error
        // is the SHELL's, not printf's. Wrapping the whole write in a
        // subshell with the subshell's stderr redirected DOES catch it —
        // `( printf ... > file ) 2>/dev/null`. Keeps the runner output
        // clean even when a node is momentarily unwritable.
        if (chmodLock) appendLine("[ -e $path ] && ( chmod 666 $path ) 2>/dev/null")
        appendLine("[ -e $path ] && ( printf %s '$khz' > $path ) 2>/dev/null")
        if (chmodLock) appendLine("[ -e $path ] && ( chmod 444 $path ) 2>/dev/null")
    }

    private fun StringBuilder.emitGovernorWrite(policyId: Int, governor: String) {
        val path = "/sys/devices/system/cpu/cpufreq/policy$policyId/scaling_governor"
        // Governors aren't policed by perfd the way freq caps are, so no
        // chmod sandwich needed. Subshell-wrap so a redirect-create
        // failure (EINVAL: governor not in this kernel) stays quiet.
        appendLine("[ -e $path ] && ( printf %s '$governor' > $path ) 2>/dev/null")
    }

    private fun StringBuilder.emitGpuWrite(gpuRoot: String, relativePath: String, value: String) {
        val path = "$gpuRoot/$relativePath"
        // GPU freq writes on Adreno KGSL also benefit from the chmod
        // sandwich because msm-adreno-tz can override caps. We do it
        // unconditionally for safety — chmod-on-non-existent path is
        // a harmless error. Subshell-wrap the write so a redirect-create
        // failure stays out of the runner output.
        appendLine("[ -e $path ] && ( chmod 666 $path ) 2>/dev/null")
        appendLine("[ -e $path ] && ( printf %s '$value' > $path ) 2>/dev/null")
        appendLine("[ -e $path ] && ( chmod 444 $path ) 2>/dev/null")
    }
}
