package io.github.mayusi.calibratesoc.data.capability

import android.content.Context
import android.content.Intent
import dagger.hilt.android.qualifiers.ApplicationContext
import io.github.mayusi.calibratesoc.data.util.toSafeFilename
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Builds a shareable "I have an unknown device, please add an adapter"
 * payload from the current [CapabilityReport]. The payload is two
 * parts:
 *   - A pre-formatted markdown body suitable for a GitHub Issue.
 *   - The full CapabilityReport JSON appended in a code fence.
 *
 * Privacy: we copy nothing the user didn't already publicly broadcast.
 * BUT we also don't dump IMEIs, serial numbers, or installed-app lists
 * — only the fields we'd genuinely use to write a device adapter. The
 * report is shown to the user in the system share sheet before it goes
 * anywhere, so they can edit / cancel.
 */
@Singleton
class DeviceReportExporter @Inject constructor(
    @ApplicationContext private val context: Context,
    private val json: Json,
) {
    /**
     * Construct the share intent. Caller invokes Activity.startActivity
     * via Intent.createChooser to surface the system share sheet —
     * keeping the choice of GitHub vs Discord vs email out of our code.
     */
    fun buildShareIntent(report: CapabilityReport): Intent {
        val title = "Calibrate SoC — unknown device adapter request"
        val body = buildMarkdownBody(report)

        return Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_SUBJECT, title)
            putExtra(Intent.EXTRA_TEXT, body)
        }.let { Intent.createChooser(it, title) }
    }

    /**
     * Write the full report to /sdcard/CalibrateSoC/device_report_<model>.json
     * so the dev (or the user pulling it via adb) can grab it without
     * needing to click through a share sheet. Returns the absolute path
     * on success, or null if the write failed.
     *
     * Filename includes the model so plugging in multiple devices over
     * a session doesn't clobber prior reports — useful when the user is
     * iterating on a new handheld (Retroid Pocket 6, AYANEO Pocket DS,
     * AYN Thor, etc.) and pasting each one in turn.
     */
    fun writeToDisk(report: CapabilityReport): String? = runCatching {
        val safeModel = toSafeFilename(report.device.model, "unknown")
        @Suppress("DEPRECATION")
        val pub = android.os.Environment.getExternalStorageDirectory()
        val dir = java.io.File(pub, "CalibrateSoC").apply { mkdirs() }
        val out = java.io.File(dir, "device_report_$safeModel.json")
        out.writeText(buildMarkdownBody(report))
        out.absolutePath
    }.getOrNull()

    private fun buildMarkdownBody(report: CapabilityReport): String {
        val reportJson = json.encodeToString(report)
        return buildString {
            appendLine("### Device adapter request")
            appendLine()
            appendLine("- **Device**: ${report.device.manufacturer} ${report.device.model}")
            appendLine("- **SoC**: ${report.soc.socManufacturer} ${report.soc.socModel}")
            appendLine("- **GPU family** (heuristic): ${report.soc.gpuFamily}")
            appendLine("- **Android**: ${report.device.androidVersion} (API ${report.device.sdkInt})")
            appendLine("- **Privilege**: ${report.privilege}")
            appendLine("- **CPU policies discovered**: ${report.cpuPolicies.size}")
            report.cpuPolicies.forEach { policy ->
                val freqs = policy.availableFreqsKhz
                appendLine(
                    "  - policy${policy.policyId}: cores ${policy.onlineCores.joinToString(",")}, " +
                        "${freqs.size} OPP steps (${(freqs.firstOrNull() ?: 0) / 1000}–${(freqs.lastOrNull() ?: 0) / 1000} MHz), " +
                        "governors: ${policy.availableGovernors.joinToString(",")}",
                )
            }
            report.gpu?.let { gpu ->
                appendLine("- **GPU**: ${gpu.family} at `${gpu.rootPath}`")
            }
            appendLine("- **Thermal zones**: ${report.thermalZones.size}")
            appendLine()
            appendLine("### Full capability report")
            appendLine()
            appendLine("```json")
            appendLine(reportJson)
            appendLine("```")
            appendLine()
            appendLine("_Generated by Calibrate SoC. Review before sharing — no IMEIs, serial numbers, or installed-app lists are included._")
        }
    }
}
